version: '3.8'
services:
  dev-db:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5456123
      POSTGRES_DB: postgres
    networks:
      - dev-network
networks:
  dev-network:
