sonar.projectKey=translator-bot
sonar.organization=your-organization

# Це ім'я та версія відображаються в SonarQube UI
sonar.projectName=Translator Bot
sonar.projectVersion=3.1.0

# Шляхи до вихідного коду
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/*.spec.ts,src/flow-editor/public/**/*

# Покриття коду тестами
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml

# Дублікація коду
sonar.cpd.exclusions=src/flow-editor/public/**

# Кодування вихідного коду
sonar.sourceEncoding=UTF-8 