receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25

  resourcedetection:
    detectors: [env, system]
    timeout: 10s

  attributes:
    actions:
      - key: service.name
        action: upsert
        value: "translator-bot"
      - key: deployment.environment
        action: upsert
        value: "production"

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:9464
    namespace: translator_bot
    const_labels:
      app: "translator-bot"

  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [jaeger, otlp/jaeger, logging]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [prometheus, logging]
  
  telemetry:
    logs:
      level: "info" 